//
//  ADDiscoveryDeviceButton.m
//  PaintProjector
//
//  Created by 文杰 胡 on 2/4/15.
//  Copyright (c) 2015 WenjiHu. All rights reserved.
//

#import "ADDiscoveryDeviceButton.h"

@implementation ADDiscoveryDeviceButton

- (id)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        // Initialization code
//        self.backgroundColor = [UIColor redColor];
    }
    return self;
}

/*
// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
- (void)drawRect:(CGRect)rect
{
    // Drawing code
}
*/
- (void)drawRect:(CGRect)rect{
    [self drawADSharedRoundButtonWithFrame:rect isSelected:self.selected || self.highlighted];
}

- (void)drawADSharedRoundButtonWithFrame: (CGRect)frame isSelected: (BOOL)isSelected
{
    
    //// Variable Declarations
    BOOL isNormal = !isSelected;
    
    
    //// Subframes
    CGRect aDSearchDeviceButton = CGRectMake(CGRectGetMinX(frame) + 6, CGRectGetMinY(frame) + 6, CGRectGetWidth(frame) - 12, CGRectGetHeight(frame) - 12);
    
    
    //// ADSearchDeviceButton
    {
        if (isNormal)
        {
            //// Normal 5
            {
                //// Bezier 9 Drawing
                UIBezierPath* bezier9Path = UIBezierPath.bezierPath;
                [bezier9Path moveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57144 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00004 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57294 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00531 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57143 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + -0.00000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57196 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00188 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 1.00000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.50000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.81451 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.04059 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 1.00000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.24864 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57143 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.99494 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 1.00000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.75189 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.81374 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.96028 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57143 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.88636 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57143 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.96181 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57143 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.91590 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.89286 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.50000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.75430 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.85279 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.89286 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.69258 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.89148 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.46692 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.89286 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.48886 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.89239 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.47782 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.64973 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.13669 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.87901 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.31733 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.78273 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.19156 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.64286 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.25000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.63562 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.13086 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.64286 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.25000 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.50000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00000 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57143 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00000 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57144 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00004 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path closePath];
                [bezier9Path moveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.11363 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.30422 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.15933 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.38404 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.12180 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.34213 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.13749 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.30045 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.16152 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.10714 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.50000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.18475 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.22988 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.10714 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.35588 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.35466 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.86509 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.10714 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.66563 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.20964 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.80731 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.35714 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.75000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.36739 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.87017 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.35714 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.75000 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.50000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 1.00000 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 1.00000 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42706 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.99469 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 1.00000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42804 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.99812 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.00000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.50000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.18549 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.95941 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + -0.00000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.75136 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.19626 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.10280 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.00000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.33810 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.07695 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.19417 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.20205 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.09843 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.24526 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.06967 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.21592 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.08812 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.23034 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.07852 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.28543 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.04825 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.25828 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.06194 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.27168 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.05479 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.39728 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.01057 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.32064 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.03150 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.35812 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.01874 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00507 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.40759 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00841 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.41803 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00658 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.11363 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.03819 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.08409 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier9Path closePath];
                [ADSharedUIStyleKit.cNormal setFill];
                [bezier9Path fill];
            }
        }
        
        
        if (isSelected)
        {
            //// Selected 5
            {
                //// Bezier 11 Drawing
                UIBezierPath* bezier11Path = UIBezierPath.bezierPath;
                [bezier11Path moveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57144 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00004 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57294 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00531 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57143 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + -0.00000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57196 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00188 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 1.00000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.50000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.81451 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.04059 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 1.00000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.24864 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57143 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.99494 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 1.00000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.75189 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.81374 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.96028 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57143 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.88636 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57143 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.96181 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57143 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.91590 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.89286 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.50000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.75430 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.85279 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.89286 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.69258 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.89148 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.46692 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.89286 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.48886 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.89239 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.47782 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.64973 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.13669 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.87901 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.31733 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.78273 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.19156 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.64286 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.25000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.63562 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.13086 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.64286 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.25000 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.50000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00000 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57143 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00000 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.57144 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00004 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path closePath];
                [bezier11Path moveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.11363 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.30422 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.15933 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.38404 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.12180 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.34213 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.13749 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.30045 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.16152 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.10714 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.50000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.18475 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.22988 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.10714 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.35588 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.35466 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.86509 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.10714 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.66563 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.20964 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.80731 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.35714 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.75000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.36739 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.87017 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.35714 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.75000 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.50000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 1.00000 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 1.00000 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42706 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.99469 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 1.00000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42804 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.99812 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.00000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.50000 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.18549 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.95941 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + -0.00000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.75136 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.19626 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.10280 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.00000 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.33810 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.07695 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.19417 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addLineToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.20205 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.09843 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.24526 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.06967 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.21592 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.08812 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.23034 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.07852 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.28543 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.04825 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.25828 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.06194 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.27168 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.05479 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.39728 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.01057 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.32064 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.03150 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.35812 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.01874 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00507 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.40759 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00841 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.41803 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.00658 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path addCurveToPoint: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.11363 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint1: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.03819 * CGRectGetHeight(aDSearchDeviceButton)) controlPoint2: CGPointMake(CGRectGetMinX(aDSearchDeviceButton) + 0.42857 * CGRectGetWidth(aDSearchDeviceButton), CGRectGetMinY(aDSearchDeviceButton) + 0.08409 * CGRectGetHeight(aDSearchDeviceButton))];
                [bezier11Path closePath];
                [ADSharedUIStyleKit.cSelected setFill];
                [bezier11Path fill];
            }
        }
    }
}

@end
