//
//  ADSharedUIStyleKit.m
//  AnaDraw
//
//  Created by Wenjie Hu on 2/5/15.
//  Copyright (c) 2015 Dreapp. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "ADSharedUIStyleKit.h"


@implementation ADSharedUIStyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
}

@end
