//
//  ADSharedUIStyleKit.h
//  AnaDraw
//
//  Created by Wenjie Hu on 2/5/15.
//  Copyright (c) 2015 Dreapp. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface ADSharedUIStyleKit : NSObject

// Drawing Methods
+ (void)drawCanvas1;

@end
