//
//  ADSharedUIStyleKit.h
//  AnaDraw
//
//  Created by Wenjie Hu on 2/5/15.
//  Copyright (c) 2015 Dreapp. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface ADSharedUIStyleKit : NSObject

// Colors
+ (UIColor*)cSelected;
+ (UIColor*)cNormal;
+ (UIColor*)cToolBarBackground;
+ (UIColor*)cHidden;
+ (UIColor*)cToolViewBackground;
+ (UIColor*)cText;
+ (UIColor*)cDisable;

// Drawing Methods
+ (void)drawTopDownBarWithFrame: (CGRect)frame;
+ (void)drawADSharedSubButtonWithIsSelected: (BOOL)isSelected;
+ (void)drawPanelBackgourndWithFrame: (CGRect)frame;
+ (void)drawADPaintColorButtonWithFrame: (CGRect)frame;
+ (void)drawADRadiusSliderWithFrame: (CGRect)frame;
+ (void)drawADOpacitySliderWithFrame: (CGRect)frame;
+ (void)drawADSharedRoundButtonWithFrame: (CGRect)frame isSelected: (BOOL)isSelected;

@end
